services:

  backend:
    build: ./
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`canvas.maxcurzi.com`)
      - traefik.docker.network=traefik-public
    networks:
      # Use the public network created to be shared
      - traefik-public

networks:
  traefik-public:
    external: true
